import { faker } from '@faker-js/faker';
import { SlugDomainService } from './slug.domain-service';

describe('SlugDomainService', () => {
  let service: SlugDomainService;

  beforeEach(() => {
    service = new SlugDomainService();
  });

  // ─── generate() ─────────────────────────────────────────────────────────────

  describe('generate()', () => {
    it('should convert title to lowercase', () => {
      expect(service.generate('TSHIRT')).toBe('tshirt');
    });

    it('should replace spaces with underscores', () => {
      expect(service.generate('T Shirt Men')).toBe('t_shirt_men');
    });

    it('should remove special characters', () => {
      // '-' is removed without leaving a space: 't-shirt' → 'tshirt'
      expect(service.generate('T-Shirt Men')).toBe('tshirt_men');
    });

    it('should remove accents (NFD normalization)', () => {
      expect(service.generate('Camiseta Básica')).toBe('camiseta_basica');
      expect(service.generate('Ñoño')).toBe('nono');
    });

    it('should collapse multiple spaces into a single underscore', () => {
      expect(service.generate('T  Shirt   Men')).toBe('t_shirt_men');
    });

    it('should strip leading and trailing underscores', () => {
      // Input that would produce leading/trailing underscores after processing
      expect(service.generate('  hello  ')).toBe('hello');
    });

    it('should remove numbers with 5 or more digits', () => {
      expect(service.generate('Product 123456')).toBe('product');
      // 4-digit numbers are kept
      expect(service.generate('Size 2024')).toBe('size_2024');
    });

    it('should collapse repeated characters (3+ in a row to 2)', () => {
      expect(service.generate('aaaa')).toBe('aa');
      expect(service.generate('cooool')).toBe('cool');
    });

    it('should throw when input is an empty string', () => {
      expect(() => service.generate('')).toThrow('Input cannot be empty for slug generation');
    });

    it('should throw when input is only whitespace', () => {
      expect(() => service.generate('   ')).toThrow('Input cannot be empty for slug generation');
    });

    it('should throw when result would be empty after processing', () => {
      // All special chars that get stripped, leaving nothing
      expect(() => service.generate('---')).toThrow();
    });

    it('should handle random product names from faker without throwing', () => {
      // Run 20 random product names — none should throw
      const titles = Array.from({ length: 20 }, () => faker.commerce.productName());
      titles.forEach((title) => {
        expect(() => service.generate(title)).not.toThrow();
      });
    });

    it('should always return a lowercase result', () => {
      const titles = Array.from({ length: 10 }, () => faker.commerce.productName());
      titles.forEach((title) => {
        const result = service.generate(title);
        expect(result).toBe(result.toLowerCase());
      });
    });

    it('should always return a result matching valid slug pattern', () => {
      const titles = Array.from({ length: 10 }, () => faker.commerce.productName());
      titles.forEach((title) => {
        const result = service.generate(title);
        expect(result).toMatch(/^[a-z0-9][a-z0-9_]*[a-z0-9]$|^[a-z0-9]$/);
      });
    });
  });

  // ─── isValid() ──────────────────────────────────────────────────────────────

  describe('isValid()', () => {
    it('should return true for a valid slug', () => {
      expect(service.isValid('t_shirt_men')).toBe(true);
      expect(service.isValid('product123')).toBe(true);
      expect(service.isValid('a')).toBe(true);
    });

    it('should return false for a slug with uppercase letters', () => {
      expect(service.isValid('T_shirt')).toBe(false);
    });

    it('should return false for a slug starting with underscore', () => {
      expect(service.isValid('_shirt')).toBe(false);
    });

    it('should return false for a slug ending with underscore', () => {
      expect(service.isValid('shirt_')).toBe(false);
    });

    it('should return false for a slug with special characters', () => {
      expect(service.isValid('t-shirt')).toBe(false);
      expect(service.isValid('t shirt')).toBe(false);
    });

    it('should return false for an empty string', () => {
      expect(service.isValid('')).toBe(false);
    });

    it('slugs generated by generate() should always pass isValid()', () => {
      const titles = Array.from({ length: 15 }, () => faker.commerce.productName());
      titles.forEach((title) => {
        const slug = service.generate(title);
        expect(service.isValid(slug)).toBe(true);
      });
    });
  });
});
